name: workflow.yml
on:
  push:
    tags:
      - 'v0.*'
      - 'draft-*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: mkdir build
      - run: cmake -B build -DCMAKE_CXX_STANDARD=11
      - run: cmake --build build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: build/PN532.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          draft: true
          fail_on_unmatched_files: true

