name: workflow.yml
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: mkdir build
      - run: cd build
      - run: cmake ..
