name: workflow.yml
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: mkdir build
      - run: cmake -B build -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/*.exe
          draft: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
