name: workflow.yml
on: push

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: mkdir build
      - run: cmake -B build -DCMAKE_CXX_STANDARD=11
      - run: cmake --build build
